version: '3'
services:
  back-end:
    build:
      context: back-end
      args:
        DISABLE_TESTS: 'true'
    ports:
      - "8080:8080"

  front-end:
    build:
      context: front-end
      args:
        DISABLE_TESTS: 'true'
    ports:
      - "3000:3000"
    depends_on:
      - back-end
