services:
  back-end:
    build:
      context: back-end
    ports:
      - 8080:8080
    environment:
      DISABLE_TESTS: "true"

  front-end:
    build:
      context: front-end
    ports:
      - 3000:3000
    depends_on:
      - back-end
